spring:
  application:
    name: cinnamon-bay-backend
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://yamabiko.proxy.rlwy.net:17387/railway?useSSL=false&serverTimezone=UTC}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:MpEbtwHnCBHEKMniWDUcvPBMFnHVbhzZ}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

server:
  port: ${PORT:8080}


auth:
  token:
    jwtSecret: ${JWT_SECRET:36763979244226452948404D635166546A576D5A7134743777217A25432A462D}
    expirationInMils: ${JWT_EXPIRATION:3600000}

logging:
  level:
    com.cinnamonbay.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.cinnamonbay.backend.security.jwt.AuthTokenFilter: DEBUG